.TH "lsl::timeout_error" 3 "Wed May 15 2019" "lslpub_ESP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lsl::timeout_error \- Exception class that indicates that an operation failed due to a timeout\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <lsl_cpp\&.h>\fP
.PP
Inherits runtime_error\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtimeout_error\fP (const std::string &msg)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Exception class that indicates that an operation failed due to a timeout\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for lslpub_ESP from the source code\&.
